/**
 * TownScene.js — town generated by generators/town.js. Stepping on the
 * worldExit marker (the stairs-up sprite on the external road's entry
 * tile) returns the player to the overworld at the town-entrance tile.
 */

import MapScene from './MapScene.js';
import { generateTown } from '../generators/town.js';
import { generateWorld } from '../generators/world.js';
import { renderTownTile } from '../autotileRender.js';
import { seedFor } from '../save.js';
import { stampRoofs } from '../../utils/roofs.js';

const TOWN_STYLES = {
  grass:      'day grass floor',
  street:     'day stone floor',
  mainStreet: 'day brick floor',
  floor:      'day tile floor',
  wall:       'bright brick wall',
  tree:       'light oak',
};

export default class TownScene extends MapScene {
  constructor() { super('Town'); }

  /** Build the town manifest, merging caller overrides from the registry. */
  buildManifest(save) {
    const manifests = this.registry.get('manifests') || {};
    return { seed: seedFor('Town', save.seed), ...(manifests.town || {}) };
  }

  generate(save) {
    const map = generateTown(this.buildManifest(save));
    // Roofs are stamped HERE rather than in the generator because
    // autotiling them needs the atlas's name lookup, and the generators
    // are deliberately atlas-free — they describe a town, they do not
    // choose sprites for it.
    const roofs = map.manifest?.roofs;
    if (roofs?.enabled !== false) {
      const atlas = this.registry.get('atlas');
      stampRoofs(map.tiles, map.buildings, {
        theme: roofs?.theme,
        byName: atlas?.byName || {},
      });
    }
    return map;
  }

  /** Terracotta over morning grass, unless the manifest says otherwise. */
  roofTheme() {
    return this.map?.manifest?.roofs?.theme;
  }

  renderTileLayers(tiles, x, y, byName) {
    return renderTownTile(tiles, x, y, TOWN_STYLES, byName);
  }

  defaultSpawn(map) {
    // On a fresh entry, drop the player ONE TILE INSIDE the worldExit so
    // they don't immediately step back out. Falls back to the exit tile
    // itself if that's the only walkable option.
    const exit = map.markers.worldExit;
    if (!exit) return { x: 1, y: 1 };
    const candidates = [
      { x: exit.x + 1, y: exit.y },
      { x: exit.x - 1, y: exit.y },
      { x: exit.x,     y: exit.y + 1 },
      { x: exit.x,     y: exit.y - 1 },
    ];
    for (const c of candidates) if (map.walkable(c.x, c.y)) return c;
    return exit;
  }

  handleMarker(marker /* , map */) {
    if (marker === 'worldExit') {
      // Return to overworld next to the town marker so the player can
      // immediately walk away without re-triggering it. Use the SAME
      // world manifest the WorldScene will use to render — otherwise
      // our spawn-candidate computation would diverge from the actual
      // world geometry.
      const save = this.registry.get('save');
      const manifests = this.registry.get('manifests') || {};
      const world = generateWorld({
        seed: seedFor('World', save.seed),
        ...(manifests.world || {}),
      });
      const t = world.markers.townEntrance;
      let spawn = { x: t.x, y: t.y + 1 };
      if (!world.walkable(spawn.x, spawn.y)) spawn = { x: t.x - 1, y: t.y };
      if (!world.walkable(spawn.x, spawn.y)) spawn = { x: t.x, y: t.y - 1 };
      this.transitionTo('World', spawn);
    }
  }

  areaLabel() { return 'Town'; }
}
